import Head from "next/head";
import Form from "../components/Form";
import Button from "../components/Button";

export default function Login() {
  return (
    <>
      <Head>
        <title>Login | BPA FMIPA&apos;21 ITB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full justify-center items-center mb-8">
        <h1 className={"text-5xl font-bold"}>LOG IN</h1>
      </div>
      <Form
        divClass={"flex flex-col w-full justify-center items-center"}
        id={"nim"}
        label={"NIM TPB"}
        type={"text"}
        placeholder={"10121000"}
        onChange={() => {
          true;
        }}
      />
      <Form
        divClass={"flex flex-col w-full justify-center items-center"}
        id={"password"}
        label={"Password"}
        type={"password"}
        placeholder={"Password"}
        onChange={() => {
          true;
        }}
      />
      <Button
        onClick={() => true}
        className={"bg-neutral-800 hover:bg-neutral-700"}
        link={"/login"}
        content={"LOG IN"}
      />
    </>
  );
}
