import Head from "next/head";
import Form from "../components/Form";
import Button from "../components/Button";

import { useState, useEffect } from "react";

import { prisma } from "../db.ts";
import Router, { useRouter } from "next/router";

export default function Login({ dataUser }) {
  const [nim, setNIM] = useState("");
  const [password, setPassword] = useState("");

  const handleNimChange = (event) => {
    setNIM(event.target.value);
  };

  const handlePasswordChange = (event) => {
    setPassword(event.target.value);
  };

  const checkLogin = (user) => {
    if (user.password === password && user.nim === nim) {
      Router.push({
        pathname: "/dashboard",
        query: { userLoggedIn: JSON.stringify(user) },
      });
      // localStorage.setItem("loggedInUser", JSON.stringify(user));
      // console.log(JSON.parse(localStorage.loggedInUser));
      // Router.push({
      //   pathname: "/dashboard",
      //   query: { userLoggedIn: localStorage.getItem("loggedInUser") },
      // });
    } else if (user.nim !== nim) {
      alert("NIM anda tidak terdaftarkan!");
    } else if (user.password !== password) {
      alert("Password anda salah!");
    }
  };

  return (
    <>
      <Head>
        <title>Login | BPA FMIPA&apos;21 ITB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full justify-center items-center mb-8">
        <h1 className={"text-5xl font-bold text-white"}>LOG IN</h1>
      </div>
      <Form
        divClass={"flex flex-col w-full justify-center items-center"}
        id={"nim"}
        label={"NIM TPB"}
        type={"text"}
        placeholder={"10121000"}
        onChange={handleNimChange}
      />
      <Form
        divClass={"flex flex-col w-full justify-center items-center"}
        id={"password"}
        label={"Password"}
        type={"password"}
        placeholder={"Password"}
        onChange={handlePasswordChange}
      />
      <Button
        onClick={() => {
          dataUser.forEach((user) => {
            console.log(user);
          });
          dataUser.forEach(checkLogin);
        }}
        className={"bg-neutral-800 hover:bg-neutral-700"}
        link={"/login"}
        content={"LOG IN"}
        textColor={"white"}
      />
    </>
  );
}

export async function getStaticProps() {
  const dataUser = await prisma.user.findMany();

  return {
    props: {
      dataUser,
    },
  };
}
